default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5432
  host: localhost
  port: 5432

development:
  <<: *default
  database: twilio_rails
  username: postgres
  password: postgres

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>